// 表格数据请求
export const SOURCESET_REQUESTED = 'SOURCESET_REQUESTED';
export const SOURCESET_SUCCEEDED = 'SOURCESET_SUCCEEDED';
export const SOURCESET_FAILED = 'SOURCESET_FAILED';

// 请求
export const SOURCECHANGE_FILTER = 'SOURCECHANGE_FILTER';
export const SOURCECHANGE_PAGE = 'SOURCECHANGE_PAGE';

// 删除
export const SOURCESET_DEL = 'SOURCESET_DEL';
